<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [19]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
                                                                  
def matrix(rows, cols):
    # Initialize matrix
    matrix = []
    print("Enter the entries rowwise:")
    # For user input
    for i in range(rows):          # for loop for row entries
        a =[]
        for j in range(cols):      # for loop for column entries
             a.append(int(input()))
        matrix.append(a)
    return matrix


def matrix_mul(A, B):
    # write your code
    if len(A[0])==len(B):
        rows, cols = len(A),len(B[0])
    
        mul = [ ([0]*cols) for i in range(rows)]
        for i in range(len(A)):
            for j in range(len(B[0])):
                for k in range(len(B)):
                    mul[i][j]+=A[i][k]*B[k][j]
        res = print(f"The Matrix multiplication of {A} and {B} is A*B = {mul} ")

        return res

    
row_A = int(input("Enter the number of rows of first matrix : ")) 
col_A = int(input("Enter the number of columns of first matrix : ")) 
row_B = int(input("Enter the number of rows of second matrix : ")) 
col_B = int(input("Enter the number of columns of second matrix : ")) 

if col_A==row_B:
    A = matrix(rows = row_A, cols = col_A)
    print(A)
    B = matrix(rows = row_B, cols = col_B)
    matrix_mul(A, B)
else:
    print(f"The Matrix multiplication of given dimension is not possible " )
    


Enter the number of rows of first matrix : 3
Enter the number of columns of first matrix : 3
Enter the number of rows of second matrix : 3
Enter the number of columns of second matrix : 3
Enter the entries rowwise:
1
3
4
2
5
7
5
9
6
[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
Enter the entries rowwise:
1
0
0
0
1
0
0
0
1
The Matrix multiplication of [[1, 3, 4], [2, 5, 7], [5, 9, 6]] and [[1, 0, 0], [0, 1, 0], [0, 0, 1]] is A*B = [[1, 3, 4], [2, 5, 7], [5, 9, 6]] 


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [5]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure

input_string = input('Enter elements of a list separated by space ')
user_list = input_string.split()
    
for i in range(len(user_list)):
    # convert each item to int type
    user_list[i] = int(user_list[i])
    
def normalize_list(user_list):
    sum = 0
    for i in user_list:
        sum += i
    
    temp = []
    for i in user_list:
        c = i/sum
        temp.append(c)
    norm_list = temp
    return norm_list
    
def pick_a_number_from_list(user_list):
    # your code here for picking an element from with the probability propotional to its magnitude
   
    rand_val = random.uniform(0,1)
    for i in range(len(user_list)):
        if rand_val<=normalize_list(user_list)[i]:
            print(user_list[i])
            break

    

def sampling_based_on_magnitued():
    for i in range(100):
        number = pick_a_number_from_list(user_list)
        if number != None:
            print(number)
        else:
            continue

sampling_based_on_magnitued()

Enter elements of a list separated by space 0 5 27 6 13 28 100 45 10 79
100
100
100
27
27
27
100
100
100
5
100
100
27
27
100
100
100
100
100
27
100
5
100
27
100
100
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [21]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program

import string
String = input('Enter the string:')

def replace_digits(String):
    str_new = []
    for i in String:
        if i in string.digits:
            str_new.append("#")
    res = print("".join(str_new))
    return res

replace_digits(String)

Enter the string:a2b3c4
###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure

import math 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

def display_dash_board(stud_lst, marks):
    
    dic_lst = dict(zip(stud_lst, marks))
    
    # write code for computing top top 5 students
    top_5_students = []
    for key, value in sorted(dic_lst.items(), key=lambda item: item[1],reverse=True)[:5]:
        top_5_students.append(key)
        
    # write code for computing top least 5 students        
    least_5_students= []    
    for key, value in sorted(dic_lst.items(), key=lambda item: item[1], reverse=False)[:5]:    
        least_5_students.append(key)
        
    # write code for computing between >25th percentile <75th percentile, in the increasing order of marks
    students_within_25_and_75 = []
    for key,value in list(sorted(dic_lst.items(), key=lambda item: item[1]))[math.ceil(len(marks) / 4):math.floor(3 * len(marks) / 4)]:
        students_within_25_and_75.append(key)    
    
    
    return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(stud_lst=Students, marks = Marks)

print(f"Top 5 Students are :{top_5_students}\n")
print(f"Top least 5 Students are :{least_5_students}\n")
print(f"Students who score  within 25 to 75 percentile  are :{students_within_25_and_75}")


Top 5 Students are :['student8', 'student10', 'student2', 'student5', 'student7']

Top least 5 Students are :['student3', 'student4', 'student9', 'student6', 'student1']

Students who score  within 25 to 75 percentile  are :['student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [10]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2


set_pt = [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
qu_pt = (3,-4)

res = []

def cal_cosdis(x_i,qu = qu_pt):
    (x,y) =x_i
    (p,q) = qu
    
    val = ((x*p+y*q)/(math.sqrt(x**2+y**2)*math.sqrt(p**2+q**2)))

    invcos_val = math.acos(val)
   
    return invcos_val

for i in set_pt:
    dist = cal_cosdis(x_i=i)
    res.append(dist)

dic_lst = dict(zip(set_pt, res))
least_5_distances = []
for k,v in sorted (dic_lst.items(), key = lambda item: item[1], reverse = False)[:5]:
    least_5_distances.append(k)
print(f"Top 5 nearest distance to query points are :{least_5_distances}\n")


Top 5 nearest distance to query points are :[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]



<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [11]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure

import math


def i_am_the_one(red_pt,blue_pt,line):
    
    flag_red = -1
    
    if eval(line.replace('x', '*%s' % red_pt[0][0]).replace('y', '*%s' % red_pt[0][1])) > 0:
        flag_red = 1
        
    for r_pt, b_pt in zip(red_pt,blue_pt):
        
        if flag_red == 1 and eval(line.replace('x', '*%s' % r_pt[0]).replace('y', '*%s' % r_pt[1])) <0:
            return 'No'
        
        if flag_red == -1 and eval(line.replace('x', '*%s' % r_pt[0]).replace('y', '*%s' % r_pt[1])) >0:
            return 'No'
        
        flag_blue = -1*flag_red
    
    
        if flag_blue == 1 and eval(line.replace('x', '*%s' % b_pt[0]).replace('y', '*%s' % b_pt[1])) <0:
            return 'No'
        
        if flag_blue == -1 and eval(line.replace('x', '*%s' % b_pt[0]).replace('y', '*%s' % b_pt[1])) >0:
            return 'No'
        
    return "Yes"
    

   
Red = [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(red_pt = Red, blue_pt = Blue, line = i)
    print(yes_or_no) # the returned value
    
    

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [13]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
def curve_smoothing(seq_str):
    
    str_lst = seq_str.split(',')
    
    for i in range(len(str_lst)):
        
        if str_lst[i].isdigit():
            
            for j in range(i+1):
                str_lst[j] = int(str_lst[i])//(i+1)
                
            new_ind = i
            new_val = int(str_lst[i])
            break
            
    for k in range(new_ind+1, len(str_lst)):
        
        if str_lst[k].isdigit():
            temp_val = (new_val+ int(str_lst[k]))//(k-new_ind+1)
            
            for l in range(new_ind, k+1):
                str_lst[l] = temp_val
            new_ind = k
            new_val = int(str_lst[k])
            
    try:
        for m in range(new_ind+1, len(str_lst)):
            
            if not(str_lst[m].isdigit()):
                count_blnk = str_lst.count('_')
                break
            
        temp_new_val = new_val//(count_blnk+1)
        
        for n in range(new_ind, len(str_lst)):
            str_lst[n] = temp_new_val
            
    except:
        pass
    
    return str_lst

s =  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(seq_str = s)

print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [14]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure

def compute_conditional_probabilites(A):
    lst_F = []
    lst_S = []
    
    for i in range(len(A)):
        res = A[i][0]+A[i][1]
        lst_F.append(res)
        lst_S.append(A[i][1])
    return lst_F, lst_S
    
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

num, den = compute_conditional_probabilites(A)


print('Probability of P(F=F1|S==S1)',(num.count('F1S1')/den.count('S1')))

Probability of P(F=F1|S==S1) 0.25


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(#the above values)

#### if Order of the words  is not important 

In [15]:
def string_features(S1, S2):
    # your code
    c_words = list(set(S1.split()) & set(S2.split()))
    a = len(c_words)
    b = list(set(S1.split()) - set(S2.split()))
    
    c = list(set(S2.split()) - set(S1.split()))
    
    return a, b, c


S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

a,b,c = string_features(S1, S2)

print('Number of common words between S1, S2:',a)
print("Words in S1 but not in S2",b)
print('Words in S2 but not in S1',c)

Number of common words between S1, S2: 7
Words in S1 but not in S2 ['F', 'first', '5']
Words in S2 but not in S1 ['3', 'S', 'second']


##### if Order of the words  is  important 


In [17]:
def string_features(S1, S2):
    # your code
    c_words = list(set(S1.split()) & set(S2.split()))
    a = len(c_words)
    #b = list(set(S1.split()) - set(S2.split()))
    b = [ i for i in S1.split() if i not in S2.split()]
    #c = list(set(S2.split()) - set(S1.split()))
    c = [ i for i in S2.split() if i not in S1.split()]
    
    return a, b, c


S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

a,b,c = string_features(S1, S2)

print('Number of common words between S1, S2:',a)
print("Words in S1 but not in S2",b)
print('Words in S2 but not in S1',c)

Number of common words between S1, S2: 7
Words in S1 but not in S2 ['first', 'F', '5']
Words in S2 but not in S1 ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [18]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
import math

def compute_log_loss(A):
    sum = 0
    for i in range(len(A)):
        cal_eqn = -1/len(A)*(A[i][0]*math.log10(A[i][1]) + (1-A[i][0])*math.log10(1-A[i][1]))
        sum+=cal_eqn
    
    return sum

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
